[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"

[build]
  publish = ".presite"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
